In [1]:
import pandas as pd 
df=pd.read_csv('processed_telco.csv.xls')
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,MonthlyCharges,TotalCharges,Churn,AvgCharges,CustomerValue,EngagementScore,TenureGroup,SpendingLevel,ChargesRatio,ServicesCount
0,7590-VHVEG,Female,0,1,0,1,0,0,DSL,0,...,29.85,29.85,0,14.925000,29.85,29.85,New,Low,0.967585,0
1,5575-GNVDE,Male,0,0,0,34,1,0,DSL,1,...,56.95,1889.50,0,53.985714,1936.30,1936.30,Mid-term,Medium,32.605695,0
2,3668-QPYBK,Male,0,0,0,2,1,0,DSL,1,...,53.85,108.15,1,36.050000,107.70,107.70,New,Medium,1.971741,0
3,7795-CFOCW,Male,0,0,0,45,0,0,DSL,1,...,42.30,1840.75,0,40.016304,1903.50,1903.50,Long-term,Low,42.511547,0
4,9237-HQITU,Female,0,0,0,2,1,0,Fiber optic,0,...,70.70,151.65,1,50.550000,141.40,141.40,New,Medium,2.115063,0
5,9305-CDSKC,Female,0,0,0,8,1,1,Fiber optic,0,...,99.65,820.50,1,91.166667,797.20,797.20,New,Medium,8.152012,0
6,1452-KIOVK,Male,0,0,1,22,1,1,Fiber optic,0,...,89.10,1949.40,0,84.756522,1960.20,1960.20,Mid-term,Medium,21.635960,0
7,6713-OKOMC,Female,0,0,0,10,0,0,DSL,1,...,29.75,301.90,0,27.445455,297.50,297.50,New,Low,9.817886,0
8,7892-POOKP,Female,0,1,0,28,1,1,Fiber optic,0,...,104.80,3046.05,1,105.036207,2934.40,2934.40,Mid-term,High,28.790643,0
9,6388-TABGU,Male,0,0,1,62,1,0,DSL,1,...,56.15,3487.95,0,55.364286,3481.30,3481.30,Long-term,Medium,61.031496,0

In [7]:
pd.set_option('display.max_columns', None)
df.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,AvgCharges,CustomerValue,EngagementScore,TenureGroup,SpendingLevel,ChargesRatio,ServicesCount
0,Female,0,1,0,1,0,0,DSL,0,1,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0,14.925000,29.85,29.85,New,Low,0.967585,0
1,Male,0,0,0,34,1,0,DSL,1,0,1,0,0,0,One year,0,Mailed check,56.95,1889.50,0,53.985714,1936.30,1936.30,Mid-term,Medium,32.605695,0
2,Male,0,0,0,2,1,0,DSL,1,1,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1,36.050000,107.70,107.70,New,Medium,1.971741,0
3,Male,0,0,0,45,0,0,DSL,1,0,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0,40.016304,1903.50,1903.50,Long-term,Low,42.511547,0
4,Female,0,0,0,2,1,0,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1,50.550000,141.40,141.40,New,Medium,2.115063,0
5,Female,0,0,0,8,1,1,Fiber optic,0,0,1,0,1,1,Month-to-month,1,Electronic check,99.65,820.50,1,91.166667,797.20,797.20,New,Medium,8.152012,0
6,Male,0,0,1,22,1,1,Fiber optic,0,1,0,0,1,0,Month-to-month,1,Credit card (automatic),89.10,1949.40,0,84.756522,1960.20,1960.20,Mid-term,Medium,21.635960,0
7,Female,0,0,0,10,0,0,DSL,1,0,0,0,0,0,Month-to-month,0,Mailed check,29.75,301.90,0,27.445455,297.50,297.50,New,Low,9.817886,0
8,Female,0,1,0,28,1,1,Fiber optic,0,0,1,1,1,1,Month-to-month,1,Electronic check,104.80,3046.05,1,105.036207,2934.40,2934.40,Mid-term,High,28.790643,0
9,Male,0,0,1,62,1,0,DSL,1,1,0,0,0,0,One year,0,Bank transfer (automatic),56.15,3487.95,0,55.364286,3481.30,3481.30,Long-term,Medium,61.031496,0

In [5]:
df.drop('customerID', axis=1, inplace=True)

In [6]:
df.isnull().sum()
df.duplicated().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7011 entries, 0 to 7010
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7011 non-null   object
 1   SeniorCitizen     7011 non-null   int64
 2   Partner           7011 non-null   int64
 3   Dependents        7011 non-null   int64
 4   tenure            7011 non-null   int64
 5   PhoneService      7011 non-null   int64
 6   MultipleLines     7011 non-null   int64
 7   InternetService   7011 non-null   object
 8   OnlineSecurity    7011 non-null   int64
 9   OnlineBackup      7011 non-null   int64
 10  DeviceProtection  7011 non-null   int64
 11  TechSupport       7011 non-null   int64
 12  StreamingTV       7011 non-null   int64
 13  StreamingMovies   7011 non-null   int64
 14  Contract          7011 non-null   object
 15  PaperlessBilling  7011 non-null   int64
 16  PaymentMethod     7011 non-null   object
 17  MonthlyCharges    7011 non-null   float64
 18  TotalCharges      7011 non-null   float64
 19  Churn             7011 non-null   int64
 20  AvgCharges        7011 non-null   float64
 21  CustomerValue     7011 non-null   float64
 22  EngagementScore   7011 non-null   float64
 23  TenureGroup       7011 non-null   object
 24  SpendingLevel     7011 non-null   object
 25  ChargesRatio      7011 non-null   float64
 26  ServicesCount     7011 non-null   int64
dtypes: float64(6), int64(15), object(6)
memory usage: 1.4+ MB

In [12]:
columns=['gender', 'InternetService', 'Contract', 'PaymentMethod', 'TenureGroup','SpendingLevel']
for col in columns:
    print(f"{col}: {df[col].unique()}")

gender: ['Female' 'Male']
InternetService: ['DSL' 'Fiber optic' 'No']
Contract: ['Month-to-month' 'One year' 'Two year']
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TenureGroup: ['New' 'Mid-term' 'Long-term']
SpendingLevel: ['Low' 'Medium' 'High']

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["gender"] = le.fit_transform(df["gender"])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
contract_order = [["Month-to-month", "One year", "Two year"]]
oe = OrdinalEncoder(categories=contract_order)
df["Contract"] = oe.fit_transform(df[["Contract"]])
tenure_order = [["New", "Mid-term", "Long-term"]]
oe2 = OrdinalEncoder(categories=tenure_order)
df["TenureGroup"] = oe2.fit_transform(df[["TenureGroup"]])
spending_order = [["Low", "Medium", "High"]]
oe3 = OrdinalEncoder(categories=spending_order)
df["SpendingLevel"] = oe3.fit_transform(df[["SpendingLevel"]])

In [16]:
df = pd.get_dummies(df, columns=["InternetService", "PaymentMethod"], drop_first=True)

In [20]:
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7011 entries, 0 to 7010
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7011 non-null   int64
 1   SeniorCitizen                          7011 non-null   int64
 2   Partner                                7011 non-null   int64
 3   Dependents                             7011 non-null   int64
 4   tenure                                 7011 non-null   int64
 5   PhoneService                           7011 non-null   int64
 6   MultipleLines                          7011 non-null   int64
 7   OnlineSecurity                         7011 non-null   int64
 8   OnlineBackup                           7011 non-null   int64
 9   DeviceProtection                       7011 non-null   int64
 10  TechSupport                            7011 non-null   int64
 11  StreamingTV                            7011 non-null   int64
 12  StreamingMovies                        7011 non-null   int64
 13  Contract                               7011 non-null   float64
 14  PaperlessBilling                       7011 non-null   int64
 15  MonthlyCharges                         7011 non-null   float64
 16  TotalCharges                           7011 non-null   float64
 17  Churn                                  7011 non-null   int64
 18  AvgCharges                             7011 non-null   float64
 19  CustomerValue                          7011 non-null   float64
 20  EngagementScore                        7011 non-null   float64
 21  TenureGroup                            7011 non-null   float64
 22  SpendingLevel                          7011 non-null   float64
 23  ChargesRatio                           7011 non-null   float64
 24  ServicesCount                          7011 non-null   int64
 25  InternetService_Fiber optic            7011 non-null   int64
 26  InternetService_No                     7011 non-null   int64
 27  PaymentMethod_Credit card (automatic)  7011 non-null   int64
 28  PaymentMethod_Electronic check         7011 non-null   int64
 29  PaymentMethod_Mailed check             7011 non-null   int64
dtypes: float64(9), int64(21)
memory usage: 1.6 MB